import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

test('admin club content add forms are rendered by React from request events', () => {
  const html = `${readFileSync('admin.html', 'utf8')}\n${readFileSync('src/admin-app/admin-controller.js', 'utf8')}`;
  const main = readFileSync('src/admin-app/main.js', 'utf8');
  const forms = readFileSync('src/admin-app/club-content-forms.js', 'utf8');
  const adminAddLeague = html.match(/async function adminAddLeagueFromReact\(detail\) \{[\s\S]*?\/\/ ---- Fundraisers management/)?.[0];
  const adminAddFundraiser = html.match(/async function adminAddFundraiserFromReact\(detail\) \{[\s\S]*?\/\/ ---- Meetings management/)?.[0];
  const adminAddMeeting = html.match(/async function adminAddMeetingFromReact\(detail\) \{[\s\S]*?\/\/ --- Members/)?.[0];
  const initAdmin = html.match(/function initAdmin\(\) \{[\s\S]*?adminLoadEvents\(\);\n            adminLoadCourses\(\);\n            adminLoadLeagues\(\);\n        \}/)?.[0];

  assert.match(html, /id="adminLeagueFormReactApp"/);
  assert.match(html, /id="adminFundraiserFormReactApp"/);
  assert.match(html, /id="adminMeetingFormReactApp"/);
  assert.doesNotMatch(html, /id="adminLeagueForm"|id="lgName"|id="lgSeason"|id="lgFormat"|id="adminFundraiserForm"|id="frTitle"|id="frGoal"|id="frPaypal"|id="frBody"|id="adminMeetingForm"|id="mtDate"|id="mtTitle"|id="mtMinutes"|id="mtActions"/);
  assert.ok(adminAddLeague);
  assert.match(adminAddLeague, /adminApi\('\/admin\/leagues', \{ method: 'POST', body \}\)/);
  assert.match(adminAddLeague, /gvdg:admin-league-create-result/);
  assert.match(adminAddLeague, /adminLoadLeagues\(\)/);
  assert.doesNotMatch(adminAddLeague, /lgName|lgSeason|lgFormat|\$\('adminLeagueForm'\)\.reset/);
  assert.ok(adminAddFundraiser);
  assert.match(adminAddFundraiser, /adminApi\('\/admin\/fundraisers', \{ method: 'POST', body \}\)/);
  assert.match(adminAddFundraiser, /gvdg:admin-fundraiser-create-result/);
  assert.match(adminAddFundraiser, /adminLoadFundraisers\(\)/);
  assert.doesNotMatch(adminAddFundraiser, /frTitle|frGoal|frPaypal|frBody|\$\('adminFundraiserForm'\)\.reset/);
  assert.ok(adminAddMeeting);
  assert.match(adminAddMeeting, /adminApi\('\/admin\/meetings', \{ method: 'POST', body \}\)/);
  assert.match(adminAddMeeting, /gvdg:admin-meeting-create-result/);
  assert.match(adminAddMeeting, /adminLoadMeetings\(\)/);
  assert.doesNotMatch(adminAddMeeting, /mtDate|mtTitle|mtMinutes|mtActions|\$\('adminMeetingForm'\)\.reset/);
  assert.ok(initAdmin);
  assert.doesNotMatch(initAdmin, /\$\('adminLeagueForm'\)\.addEventListener|\$\('adminFundraiserForm'\)\.addEventListener|\$\('adminMeetingForm'\)\.addEventListener/);
  assert.match(initAdmin, /gvdg:admin-league-create-request/);
  assert.match(initAdmin, /adminAddLeagueFromReact\(event\.detail \|\| \{\}\)/);
  assert.match(initAdmin, /gvdg:admin-fundraiser-create-request/);
  assert.match(initAdmin, /adminAddFundraiserFromReact\(event\.detail \|\| \{\}\)/);
  assert.match(initAdmin, /gvdg:admin-meeting-create-request/);
  assert.match(initAdmin, /adminAddMeetingFromReact\(event\.detail \|\| \{\}\)/);
  assert.match(main, /import \{ AdminFundraiserForm, AdminLeagueForm, AdminMeetingForm \} from "\.\/club-content-forms\.js"/);
  assert.match(main, /const leagueFormMount = document\.getElementById\("adminLeagueFormReactApp"\)/);
  assert.match(main, /createRoot\(leagueFormMount\)\.render\(h\(AdminLeagueForm\)\)/);
  assert.match(main, /const fundraiserFormMount = document\.getElementById\("adminFundraiserFormReactApp"\)/);
  assert.match(main, /createRoot\(fundraiserFormMount\)\.render\(h\(AdminFundraiserForm\)\)/);
  assert.match(main, /const meetingFormMount = document\.getElementById\("adminMeetingFormReactApp"\)/);
  assert.match(main, /createRoot\(meetingFormMount\)\.render\(h\(AdminMeetingForm\)\)/);
  assert.match(forms, /export function AdminLeagueForm/);
  assert.match(forms, /export function AdminFundraiserForm/);
  assert.match(forms, /export function AdminMeetingForm/);
  assert.match(forms, /data-react-admin-league-form/);
  assert.match(forms, /data-react-admin-fundraiser-form/);
  assert.match(forms, /data-react-admin-meeting-form/);
  assert.match(forms, /gvdg:admin-league-create-request/);
  assert.match(forms, /gvdg:admin-fundraiser-create-request/);
  assert.match(forms, /gvdg:admin-meeting-create-request/);
  assert.match(forms, /gvdg:admin-league-create-result/);
  assert.match(forms, /gvdg:admin-fundraiser-create-result/);
  assert.match(forms, /gvdg:admin-meeting-create-result/);
  assert.match(forms, /id: "adminLeagueForm"/);
  assert.match(forms, /id: "adminFundraiserForm"/);
  assert.match(forms, /id: "adminMeetingForm"/);
  assert.match(forms, /status: "active"/);
  assert.match(forms, /action_items: form\.actionItems/);
  assert.doesNotMatch(forms, /innerHTML|insertAdjacentHTML|replaceChildren|document\.createElement|querySelector|classList|textContent\s*=|☰|✕|🔒|🌙|☀️|🏆|⚠|⏱|—/);
});
