import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

test('admin tee-sign review queue is rendered by React from direct loader events', () => {
  const html = `${readFileSync('admin.html', 'utf8')}\n${readFileSync('src/admin-app/admin-controller.js', 'utf8')}`;
  const teeSignController = readFileSync('src/admin-app/tee-sign-review-controller.js', 'utf8');
  const main = readFileSync('src/admin-app/main.js', 'utf8');
  const review = readFileSync('src/admin-app/tee-sign-review.js', 'utf8');
  const tsLoadReview = teeSignController.match(/async function loadReview\(detail\) \{[\s\S]*?function finishTeeSignReviewAction/)?.[0];

  assert.match(html, /id="adminTeeSignReviewControlsReactApp"/);
  assert.match(html, /id="adminTeeSignReviewReactApp"/);
  assert.doesNotMatch(html, /id="tsStatusFilter"|id="tsRefresh"|id="tsReviewList"/);
  assert.match(teeSignController, /function setAdminTeeSignReviewState\(state\) \{[\s\S]*dispatchAdminEvent\('gvdg:admin-tee-sign-review', state\)/);
  assert.doesNotMatch(`${html}\n${teeSignController}`, /publishAdminState\('teeSignReview'/);
  assert.ok(tsLoadReview);
  assert.match(tsLoadReview, /adminTeeSignReviewControlsState\(detail\)/);
  assert.match(tsLoadReview, /setAdminTeeSignReviewState\(\{ status: 'loading'/);
  assert.match(tsLoadReview, /adminApi\('\/admin\/tee-signs\?status=' \+ encodeURIComponent\(queueStatus\)\)/);
  assert.match(tsLoadReview, /setAdminTeeSignReviewState\(\{ status: 'ready'/);
  assert.doesNotMatch(tsLoadReview, /tsReviewList|replaceChildren|appendChild|document\.createElement|tsCard|tsRowsFrom|tsAddReviewRow|\$\('tsStatusFilter'\)/);
  assert.match(teeSignController, /async function tsApproveFromReact\(detail\)/);
  assert.match(teeSignController, /async function tsExtractFromReact\(detail\)/);
  assert.match(teeSignController, /async function tsRejectFromReact\(detail\)/);
  assert.match(teeSignController, /async function tsDeleteFromReact\(detail\)/);
  assert.match(teeSignController, /gvdg:admin-tee-sign-review-action-result/);
  assert.match(html, /import \{ installTeeSignReviewController \} from "\.\/tee-sign-review-controller\.js"/);
  assert.match(html, /let loadTeeSignReview = async \(\) => \{\}/);
  assert.match(html, /loadTeeSignReview = installTeeSignReviewController\(/);
  assert.match(html, /if \(tab === 'tee-signs'\) loadTeeSignReview\(\)/);
  assert.match(teeSignController, /gvdg:admin-tee-sign-review-controls-request/);
  assert.match(teeSignController, /loadReview\(event\.detail \|\| \{\}\)/);
  assert.match(teeSignController, /gvdg:admin-tee-sign-review-approve-request/);
  assert.match(teeSignController, /gvdg:admin-tee-sign-review-extract-request/);
  assert.match(teeSignController, /gvdg:admin-tee-sign-review-reject-request/);
  assert.match(teeSignController, /gvdg:admin-tee-sign-review-delete-request/);
  assert.doesNotMatch(html, /\$\('tsStatusFilter'\)\.addEventListener|\$\('tsRefresh'\)\.addEventListener/);

  assert.match(main, /import \{ AdminTeeSignReviewControls, AdminTeeSignReviewList \} from "\.\/tee-sign-review\.js"/);
  assert.match(main, /const teeSignReviewControlsMount = document\.getElementById\("adminTeeSignReviewControlsReactApp"\)/);
  assert.match(main, /createRoot\(teeSignReviewControlsMount\)\.render\(h\(AdminTeeSignReviewControls\)\)/);
  assert.match(main, /const teeSignReviewMount = document\.getElementById\("adminTeeSignReviewReactApp"\)/);
  assert.match(main, /createRoot\(teeSignReviewMount\)\.render\(h\(AdminTeeSignReviewList\)\)/);

  assert.match(review, /export function AdminTeeSignReviewControls/);
  assert.match(review, /export function AdminTeeSignReviewList/);
  assert.match(review, /data-react-admin-tee-sign-review-controls/);
  assert.match(review, /data-react-admin-tee-sign-review/);
  assert.match(review, /gvdg:admin-tee-sign-review-controls-request/);
  assert.match(review, /gvdg:admin-tee-sign-review/);
  assert.match(review, /gvdg:admin-tee-sign-review-approve-request/);
  assert.match(review, /gvdg:admin-tee-sign-review-extract-request/);
  assert.match(review, /gvdg:admin-tee-sign-review-reject-request/);
  assert.match(review, /gvdg:admin-tee-sign-review-delete-request/);
  assert.match(review, /gvdg:admin-tee-sign-review-action-result/);
  assert.doesNotMatch(review, /currentAdminState\("teeSignReview"|admin-state-store|function currentState/);
  assert.match(review, /let teeSignReviewControlsStateSnapshot = \{\}/);
  assert.doesNotMatch(review, /window\.__gvdgAdminTeeSignReviewControlsState/);
  assert.match(teeSignController, /let teeSignReviewControlsSnapshot = \{\}/);
  assert.doesNotMatch(`${html}\n${teeSignController}`, /window\.__gvdgAdminTeeSignReviewControlsState/);
  assert.match(review, /id: "tsStatusFilter"/);
  assert.match(review, /id: "tsRefresh"/);
  assert.match(review, /className: "ts-review-card"/);
  assert.match(review, /className: "ts-review-row"/);
  assert.match(review, /URL\.createObjectURL/);
  assert.match(review, /URL\.revokeObjectURL/);
  assert.doesNotMatch(review, /innerHTML|insertAdjacentHTML|replaceChildren|document\.createElement|querySelector|classList|textContent\s*=|☰|✕|🔒|🌙|☀️|🏆|⚠|⏱|—/);
});
