import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

test('admin new event form is rendered by React and saved through bridge events', () => {
  const html = `${readFileSync('admin.html', 'utf8')}\n${readFileSync('src/admin-app/admin-controller.js', 'utf8')}`;
  const main = readFileSync('src/admin-app/main.js', 'utf8');
  const eventForm = readFileSync('src/admin-app/event-form.js', 'utf8');
  const adminLoadCourses = html.match(/async function adminLoadCourses\(\) \{[\s\S]*?\n        \}/)?.[0];
  const adminLoadLeagues = html.match(/async function adminLoadLeagues\(\) \{[\s\S]*?\n        \}/)?.[0];
  const aeEditEvent = html.match(/function aeEditEvent\(ev\) \{[\s\S]*?\n        \}/)?.[0];
  const adminSaveEvent = html.match(/async function adminSaveEventFromReact\(detail\) \{[\s\S]*?\n        \}/)?.[0];
  const initAdmin = html.match(/function initAdmin\(\) \{[\s\S]*?adminLoadEvents\(\);\n            adminLoadCourses\(\);\n            adminLoadLeagues\(\);\n        \}/)?.[0];

  assert.match(html, /id="adminEventFormReactApp"/);
  assert.doesNotMatch(html, /id="adminCreateForm"[\s\S]*?<select id="aeCourse"/);
  assert.match(html, /function setAdminEventFormLayoutsState\(state\) \{[\s\S]*new CustomEvent\('gvdg:admin-event-form-layouts', \{ detail: state \}\)/);
  assert.doesNotMatch(html, /publishAdminState\('eventFormLayouts'/);
  assert.ok(adminLoadCourses);
  assert.match(adminLoadCourses, /adminCoursesCache = courses/);
  assert.match(adminLoadCourses, /setAdminCoursesListState\(\{ courses \}\)/);
  assert.doesNotMatch(adminLoadCourses, /aeCourse|document\.createElement|appendChild|textContent/);
  assert.ok(adminLoadLeagues);
  assert.match(adminLoadLeagues, /gvdg:admin-leagues-list', \{ detail: \{ leagues \} \}/);
  assert.doesNotMatch(adminLoadLeagues, /aeLeague|document\.createElement|appendChild|textContent/);
  assert.ok(aeEditEvent);
  assert.match(aeEditEvent, /adminSwitch\('create'\)/);
  assert.match(aeEditEvent, /gvdg:admin-event-form-edit/);
  assert.doesNotMatch(aeEditEvent, /\$\('aeName'\)|\$\('aeCourse'\)|\$\('aeLayout'\)|scrollIntoView/);
  assert.ok(adminSaveEvent);
  assert.match(adminSaveEvent, /adminApi\('\/admin\/events\/' \+ detail\.eventId, \{ method: 'PATCH', body \}\)/);
  assert.match(adminSaveEvent, /adminApi\('\/admin\/events', \{ method: 'POST', body: \{ \.\.\.body, source: 'manual' \} \}\)/);
  assert.match(adminSaveEvent, /gvdg:admin-event-save-result/);
  assert.ok(initAdmin);
  assert.match(initAdmin, /gvdg:admin-event-form-layouts-load-request/);
  assert.match(initAdmin, /gvdg:admin-event-save-request/);
  assert.match(initAdmin, /gvdg:admin-event-edit-cancel-request/);
  assert.doesNotMatch(initAdmin, /\$\('adminCreateForm'\)\.addEventListener|\$\('aeCourse'\)\.addEventListener|\$\('aeLayout'\)\.addEventListener|\$\('aeCancelEdit'\)\.addEventListener/);

  assert.match(main, /import \{ AdminEventForm \} from "\.\/event-form\.js"/);
  assert.match(main, /const eventFormMount = document\.getElementById\("adminEventFormReactApp"\)/);
  assert.match(main, /createRoot\(eventFormMount\)\.render\(h\(AdminEventForm\)\)/);
  assert.match(eventForm, /export function AdminEventForm/);
  assert.match(eventForm, /data-react-admin-event-form/);
  assert.match(eventForm, /React\.useLayoutEffect/);
  assert.match(eventForm, /id: "adminCreateForm"/);
  assert.match(eventForm, /id: "aeName"/);
  assert.match(eventForm, /const courseId = primary \? "aeCourse" : `aeCourse-\$\{row\.key\}`/);
  assert.match(eventForm, /const layoutId = primary \? "aeLayout" : `aeLayout-\$\{row\.key\}`/);
  assert.match(eventForm, /body\.event_courses = eventCourses/);
  assert.match(eventForm, /courseRowsFromEvent/);
  assert.match(eventForm, /Add course\/layout/);
  assert.match(eventForm, /id: "aeLeague"/);
  assert.match(eventForm, /gvdg:admin-courses-list/);
  assert.match(eventForm, /gvdg:admin-leagues-list/);
  assert.match(eventForm, /gvdg:admin-event-form-layouts/);
  assert.match(eventForm, /gvdg:admin-event-form-edit/);
  assert.match(eventForm, /gvdg:admin-event-form-reset/);
  assert.match(eventForm, /gvdg:admin-event-save-request/);
  assert.match(eventForm, /gvdg:admin-event-edit-cancel-request/);
  assert.doesNotMatch(eventForm, /currentAdminState\("coursesList"|currentAdminState\("eventFormLayouts"|admin-state-store|function currentState/);
  assert.doesNotMatch(eventForm, /innerHTML|insertAdjacentHTML|replaceChildren|document\.createElement|querySelector|classList|textContent\s*=|☰|✕|🔒|🌙|☀️/);
});
