import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

test('admin course layouts tab is rendered by React from direct loader events', () => {
  const html = `${readFileSync('admin.html', 'utf8')}\n${readFileSync('src/admin-app/admin-controller.js', 'utf8')}`;
  const layoutsController = readFileSync('src/admin-app/course-layouts-controller.js', 'utf8');
  const main = readFileSync('src/admin-app/main.js', 'utf8');
  const manager = readFileSync('src/admin-app/layouts-manager.js', 'utf8');
  const sections = readFileSync('src/admin-app/layouts-sections.js', 'utf8');
  const builder = readFileSync('src/admin-app/layouts-builder.js', 'utf8');
  const model = readFileSync('src/admin-app/layouts-model.js', 'utf8');
  const adminLoadCourses = html.match(/async function adminLoadCourses\(\) \{[\s\S]*?\n        \}/)?.[0];
  const adminSwitch = html.match(/function adminSwitch\(tab\) \{[\s\S]*?\n        \}/)?.[0];
  const adminLoadCourseLayouts = layoutsController.match(/async function loadCourseLayouts\(detail\) \{[\s\S]*?async function adminAddLayoutPositionFromReact/)?.[0];

  assert.match(html, /id="adminLayoutsReactApp"/);
  assert.doesNotMatch(html, /id="alCourse"|id="alBody"|id="alUdiscUrl"|id="alUdiscBtn"|id="alUdiscResult"|id="alPoolList"|id="alPosKind"|id="alPosLabel"|id="alPosLat"|id="alPosLng"|id="alPosAddBtn"|id="alName"|id="alHoles"|id="alAddHole"|id="alSaveLayout"|id="alResetLayout"|id="alLayoutsList"/);
  assert.doesNotMatch(html, /function alOnCourseChange|function alLoadPool|function alUdiscFetch|function posOptions|function refreshRowSelects|function addHoleRow|function renderHoleRows|function gatherHoles|function alSaveLayout|function alLoadLayouts|function alEditLayout/);
  assert.ok(adminLoadCourses);
  assert.match(adminLoadCourses, /setAdminCoursesListState\(\{ courses \}\)/);
  assert.doesNotMatch(adminLoadCourses, /alCourse|lsel/);
  assert.ok(adminSwitch);
  assert.match(adminSwitch, /if \(tab === 'layouts'\) adminLoadCourses\(\)/);
  assert.match(layoutsController, /function setAdminCourseLayoutsState\(state\) \{[\s\S]*dispatchAdminEvent\('gvdg:admin-course-layouts-state', state\)/);
  assert.doesNotMatch(`${html}\n${layoutsController}`, /publishAdminState\('courseLayouts'/);
  assert.ok(adminLoadCourseLayouts);
  assert.match(adminLoadCourseLayouts, /setAdminCourseLayoutsState\(\{ status: 'loading'/);
  assert.match(adminLoadCourseLayouts, /api\('\/courses\/' \+ encodeURIComponent\(courseId\) \+ '\/positions'\)/);
  assert.match(adminLoadCourseLayouts, /api\('\/courses\/' \+ encodeURIComponent\(courseId\) \+ '\/layouts'\)/);
  assert.match(adminLoadCourseLayouts, /setAdminCourseLayoutsState\(\{ status: 'ready'/);
  assert.doesNotMatch(adminLoadCourseLayouts, /document\.createElement|appendChild|replaceChildren|querySelector|textContent|alPoolList|alLayoutsList/);
  assert.match(layoutsController, /async function adminAddLayoutPositionFromReact\(detail\)/);
  assert.match(layoutsController, /async function adminDeleteLayoutPositionFromReact\(detail\)/);
  assert.match(layoutsController, /async function adminFetchUdiscLayoutsFromReact\(detail\)/);
  assert.match(layoutsController, /async function adminApplyUdiscLayoutFromReact\(detail\)/);
  assert.match(layoutsController, /async function adminSaveCourseLayoutFromReact\(detail\)/);
  assert.match(layoutsController, /async function adminDeleteCourseLayoutFromReact\(detail\)/);
  assert.match(layoutsController, /gvdg:admin-course-layouts-action-result/);
  assert.match(html, /import \{ installCourseLayoutsController \} from "\.\/course-layouts-controller\.js"/);
  assert.match(html, /installCourseLayoutsController\(\{ api, \.\.\.adminControllerDeps \}\)/);
  assert.match(layoutsController, /gvdg:admin-course-layouts-load-request/);
  assert.match(layoutsController, /gvdg:admin-course-layout-position-add-request/);
  assert.match(layoutsController, /gvdg:admin-course-layout-position-delete-request/);
  assert.match(layoutsController, /gvdg:admin-course-layout-udisc-fetch-request/);
  assert.match(layoutsController, /gvdg:admin-course-layout-udisc-apply-request/);
  assert.match(layoutsController, /gvdg:admin-course-layout-save-request/);
  assert.match(layoutsController, /gvdg:admin-course-layout-delete-request/);
  assert.doesNotMatch(html, /\$\('alCourse'\)\.addEventListener|\$\('alPosAddBtn'\)\.addEventListener|\$\('alUdiscBtn'\)\.addEventListener|\$\('alAddHole'\)\.addEventListener|\$\('alSaveLayout'\)\.addEventListener|\$\('alResetLayout'\)\.addEventListener/);

  assert.match(main, /import \{ AdminLayoutsManager \} from "\.\/layouts-manager\.js"/);
  assert.match(main, /const layoutsMount = document\.getElementById\("adminLayoutsReactApp"\)/);
  assert.match(main, /createRoot\(layoutsMount\)\.render\(h\(AdminLayoutsManager\)\)/);
  assert.match(manager, /export function AdminLayoutsManager/);
  assert.match(manager, /data-react-admin-layouts/);
  assert.match(manager, /React\.useLayoutEffect/);
  assert.match(manager, /gvdg:admin-courses-list/);
  assert.match(manager, /gvdg:admin-course-layouts-state/);
  assert.match(manager, /gvdg:admin-course-layouts-load-request/);
  assert.match(manager, /gvdg:admin-course-layout-position-add-request/);
  assert.match(manager, /gvdg:admin-course-layout-position-delete-request/);
  assert.match(manager, /gvdg:admin-course-layout-udisc-fetch-request/);
  assert.match(manager, /gvdg:admin-course-layout-udisc-apply-request/);
  assert.match(manager, /gvdg:admin-course-layout-save-request/);
  assert.match(manager, /gvdg:admin-course-layout-delete-request/);
  assert.match(manager, /gvdg:admin-course-layouts-action-result/);
  assert.match(manager, /id: "alCourse"/);
  assert.doesNotMatch(manager, /currentAdminState\("coursesList"|currentAdminState\("courseLayouts"|admin-state-store|function current(?:Courses|Layouts)State/);
  assert.match(sections, /export function AdminLayoutUdiscImport/);
  assert.match(sections, /export function AdminLayoutPositionPool/);
  assert.match(sections, /export function AdminLayoutsList/);
  assert.match(sections, /id: "alUdiscUrl"/);
  assert.match(sections, /id: "alPoolList"/);
  assert.match(sections, /id: "alLayoutsList"/);
  assert.match(builder, /export function AdminLayoutBuilder/);
  assert.match(builder, /className: "admin-layout-field"/);
  assert.match(builder, /className: "al-holes"/);
  assert.match(builder, /id: "alName"/);
  assert.match(builder, /id: "alSaveLayout"/);
  assert.match(builder, /estimateHole/);
  assert.match(model, /export function estimateHole/);
  assert.match(model, /export function layoutPayload/);
  assert.doesNotMatch(`${manager}\n${sections}\n${builder}\n${model}`, /innerHTML|insertAdjacentHTML|replaceChildren|document\.createElement|querySelector|classList|textContent\s*=|☰|✕|🔒|🌙|☀️|🏆|⚠|⏱|🦁|🪧|⛳|🎯|—/);
});
