import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

test('admin registration panel owns selector, settings, assignments, CTP add, and ace pot controls in React', () => {
  const html = `${readFileSync('admin.html', 'utf8')}\n${readFileSync('src/admin-app/admin-controller.js', 'utf8')}`;
  const main = readFileSync('src/admin-app/main.js', 'utf8');
  const panel = readFileSync('src/admin-app/registration-panel.js', 'utf8');
  const controls = readFileSync('src/admin-app/registration-controls.js', 'utf8');
  const actions = readFileSync('src/admin-app/registration-actions.js', 'utf8');
  const rgLoadEvents = html.match(/async function rgLoadEvents\(\) \{[\s\S]*?\n        \}/)?.[0];
  const rgSelectEvent = html.match(/async function rgSelectEventFromReact\(detail\) \{[\s\S]*?\n        \}/)?.[0];
  const rgLoadRoster = html.match(/async function rgLoadRoster\(\) \{[\s\S]*?\n        \}/)?.[0];
  const rgLoadAcePot = html.match(/async function rgLoadAcePot\(\) \{[\s\S]*?\n        \}/)?.[0];
  const initAdmin = html.match(/function initAdmin\(\) \{[\s\S]*?adminLoadEvents\(\);\n            adminLoadCourses\(\);\n            adminLoadLeagues\(\);\n        \}/)?.[0];

  assert.match(html, /id="adminRegistrationReactApp"/);
  assert.doesNotMatch(html, /id="rgBody"|id="rgSaveBtn"|id="rgAssignCards"|id="rgCtpAdd"|id="rgAceSave"|id="rgAcePayout"|id="rgAceCarryNext"/);
  assert.doesNotMatch(html, /id="adminRegistrationRosterReactApp"|id="adminRegistrationManualPlayerFormReactApp"|id="adminRegistrationCtpsReactApp"|id="adminRegistrationCreditsReactApp"|id="adminRegistrationAcePotReactApp"/);
  assert.match(html, /let adminRegistrationControlsSnapshot = \{ status: 'loading', events: \[\], selectedEventId: null, configStatus: 'idle', config: null \}/);
  assert.match(html, /function setAdminRegistrationControlsState\(state\) \{[\s\S]*adminRegistrationControlsSnapshot = next;[\s\S]*gvdg:admin-registration-controls/);
  assert.doesNotMatch(html, /window\.__gvdgAdminRegistrationControlsState/);
  assert.match(html, /function setAdminRegistrationMemberOptionsState\(state\) \{[\s\S]*new CustomEvent\('gvdg:admin-registration-member-options', \{ detail: state \}\)/);
  assert.doesNotMatch(html, /publishAdminState\('registrationMemberOptions'/);
  assert.ok(rgLoadEvents);
  assert.match(rgLoadEvents, /setAdminRegistrationControlsState\(\{ status: 'loading'/);
  assert.match(rgLoadEvents, /setAdminRegistrationControlsState\(\{ status: 'ready', events/);
  assert.doesNotMatch(rgLoadEvents, /\$\('rgEvent'\)|document\.createElement\('option'\)|appendChild|selectedOptions|\.length = 1/);
  assert.ok(rgSelectEvent);
  assert.match(rgSelectEvent, /rgEventId = selectedEventId == null \? null : Number\(selectedEventId\)/);
  assert.match(rgSelectEvent, /configStatus: 'loading'/);
  assert.match(rgSelectEvent, /rgLoadRoster\(\);[\s\S]*rgLoadCtps\(\);[\s\S]*rgLoadCredits\(\);[\s\S]*rgLoadAcePot\(\);/);
  assert.ok(rgLoadRoster);
  assert.match(rgLoadRoster, /setAdminRegistrationMemberOptionsState\(\{ status: ok \? 'ready' : 'error', options: memberOptions \}\)/);
  assert.doesNotMatch(rgLoadRoster, /\$\('rgMemberOptions'\)|replaceChildren|document\.createElement\('option'\)|appendChild/);
  assert.ok(rgLoadAcePot);
  assert.doesNotMatch(rgLoadAcePot, /\$\('rgAceCarry'\)|\.value =/);
  assert.ok(initAdmin);
  assert.match(initAdmin, /gvdg:admin-registration-event-select-request/);
  assert.match(initAdmin, /gvdg:admin-registration-config-save-request/);
  assert.match(initAdmin, /gvdg:admin-registration-assign-request/);
  assert.match(initAdmin, /gvdg:admin-registration-ctp-add-request/);
  assert.match(initAdmin, /gvdg:admin-registration-ace-pot-action-request/);
  assert.doesNotMatch(initAdmin, /\$\('rgEvent'\)\.addEventListener|\$\('rgSaveBtn'\)\.addEventListener|\$\('rgAssignCards'\)\.addEventListener|\$\('rgCtpAdd'\)\.addEventListener|\$\('rgAce/);

  assert.match(main, /import \{ AdminRegistrationPanel \} from "\.\/registration-panel\.js"/);
  assert.match(main, /const registrationMount = document\.getElementById\("adminRegistrationReactApp"\)/);
  assert.match(main, /createRoot\(registrationMount\)\.render\(h\(AdminRegistrationPanel\)\)/);
  assert.doesNotMatch(main, /adminRegistrationRosterReactApp|adminRegistrationManualPlayerFormReactApp|adminRegistrationCtpsReactApp|adminRegistrationCreditsReactApp|adminRegistrationAcePotReactApp/);

  assert.match(panel, /export function AdminRegistrationPanel/);
  assert.match(panel, /AdminRegistrationControls/);
  assert.match(panel, /AdminRegistrationRoster/);
  assert.match(panel, /AdminRegistrationManualPlayerForm/);
  assert.match(panel, /AdminRegistrationCtpsList/);
  assert.match(panel, /AdminRegistrationCreditsList/);
  assert.match(panel, /AdminRegistrationAcePot/);
  assert.match(controls, /gvdg:admin-registration-controls/);
  assert.match(controls, /let registrationControlsStateSnapshot = EMPTY_STATE/);
  assert.doesNotMatch(controls, /window\.__gvdgAdminRegistrationControlsState/);
  assert.match(controls, /value === "ready"/);
  assert.match(controls, /gvdg:admin-registration-event-select-request/);
  assert.match(controls, /gvdg:admin-registration-config-save-request/);
  assert.match(actions, /gvdg:admin-registration-member-options/);
  assert.match(actions, /id: "rgMemberOptions"/);
  assert.match(actions, /gvdg:admin-registration-assign-request/);
  assert.match(actions, /gvdg:admin-registration-ctp-add-request/);
  assert.match(actions, /gvdg:admin-registration-ace-pot-action-request/);
  assert.doesNotMatch(actions, /currentAdminState\("registrationMemberOptions"|currentAdminState\("registrationAcePot"|admin-state-store|function current(?:MemberOptions|AcePot)State/);
  assert.doesNotMatch(panel + controls + actions, /innerHTML|insertAdjacentHTML|replaceChildren|document\.createElement|querySelector|classList|textContent\s*=|☰|✕|🌙|☀️|🏆|⚠|⏱|—/);
});
