import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

test('admin registration roster is rendered by React from direct loader events', () => {
  const html = `${readFileSync('admin.html', 'utf8')}\n${readFileSync('src/admin-app/admin-controller.js', 'utf8')}`;
  const main = readFileSync('src/admin-app/main.js', 'utf8');
  const manualForm = readFileSync('src/admin-app/registration-manual-player-form.js', 'utf8');
  const panel = readFileSync('src/admin-app/registration-panel.js', 'utf8');
  const roster = readFileSync('src/admin-app/registration-roster.js', 'utf8');
  const rows = readFileSync('src/admin-app/registration-roster-rows.js', 'utf8');
  const rosterSurface = manualForm + roster + rows;
  const rgLoadRoster = html.match(/async function rgLoadRoster\(\) \{[\s\S]*?\n        \}/)?.[0];
  const rgRemoveManualPlayer = html.match(/async function rgRemoveManualPlayer\(player\) \{[\s\S]*?\n        \}/)?.[0];
  const rgAwardCredit = html.match(/async function rgAwardCredit\(memberId, name, amountValue\) \{[\s\S]*?\n        \}/)?.[0];
  const initAdmin = html.match(/function initAdmin\(\) \{[\s\S]*?adminLoadEvents\(\);\n            adminLoadCourses\(\);\n            adminLoadLeagues\(\);\n        \}/)?.[0];

  assert.match(html, /id="adminRegistrationReactApp"/);
  assert.doesNotMatch(html, /id="adminRegistrationManualPlayerFormReactApp"/);
  assert.doesNotMatch(html, /id="adminRegistrationRosterReactApp"/);
  assert.doesNotMatch(html, /id="rgRoster"|id="rgCount"/);
  assert.doesNotMatch(html, /id="rgPlayerName"|id="rgPlayerMember"|id="rgPlayerPdga"|id="rgPlayerDivision"|id="rgPlayerTeam"|id="rgPlayerAdd"/);
  assert.match(html, /function setAdminRegistrationRosterState\(state\) \{[\s\S]*new CustomEvent\('gvdg:admin-registration-roster', \{ detail: state \}\)/);
  assert.doesNotMatch(html, /publishAdminState\('registrationRoster'/);
  assert.ok(rgLoadRoster);
  assert.match(rgLoadRoster, /setAdminRegistrationRosterState\(\{ status: 'loading', registrations: \[\], manualPlayers: \[\] \}\)/);
  assert.match(html, /function setAdminRegistrationMemberOptionsState\(state\) \{[\s\S]*new CustomEvent\('gvdg:admin-registration-member-options', \{ detail: state \}\)/);
  assert.doesNotMatch(html, /publishAdminState\('registrationMemberOptions'/);
  assert.match(rgLoadRoster, /const memberOptions = regs\.filter\(\(rg\) => rg\.member_id\)\.map\(\(rg\) => \(\{ value: rg\.member_id, label: rg\.name \|\| rg\.member_id \}\)\)/);
  assert.match(rgLoadRoster, /setAdminRegistrationMemberOptionsState\(\{ status: ok \? 'ready' : 'error', options: memberOptions \}\)/);
  assert.match(rgLoadRoster, /setAdminRegistrationRosterState\(\{ status: ok \? 'ready' : 'error', registrations: regs, manualPlayers: manual \}\)/);
  assert.doesNotMatch(rgLoadRoster, /rgRoster|rgCount|thead|tbody|rgCreditCell|rgToggleCell|elx\('td'|elx\('th'|textContent|addEventListener\('change'|document\.createElement\('(?:thead|tbody|tr|td|th|input|button|span)'\)/);
  assert.ok(rgRemoveManualPlayer);
  assert.doesNotMatch(rgRemoveManualPlayer, /confirm\(/);
  assert.ok(rgAwardCredit);
  assert.match(rgAwardCredit, /dollarsToCents\(amountValue\)/);
  assert.match(rgAwardCredit, /rgLoadRoster\(\); rgLoadCredits\(\)/);
  assert.doesNotMatch(rgAwardCredit, /input\.value|memberInput|amountInput/);
  assert.ok(initAdmin);
  assert.match(initAdmin, /gvdg:admin-registration-roster-patch-request/);
  assert.match(initAdmin, /rgPatch\(registration\.id, detail\.patch \|\| \{\}\)/);
  assert.match(initAdmin, /gvdg:admin-registration-roster-credit-request/);
  assert.match(initAdmin, /rgAwardCredit\(detail\.memberId, detail\.memberName, detail\.amountValue\)/);
  assert.match(initAdmin, /gvdg:admin-registration-manual-remove-request/);
  assert.match(initAdmin, /rgRemoveManualPlayer\(player\)/);
  assert.match(initAdmin, /gvdg:admin-registration-manual-player-add-request/);
  assert.match(initAdmin, /rgAddManualPlayerFromReact\(event\.detail \|\| \{\}\)/);
  assert.doesNotMatch(initAdmin, /\$\('rgPlayerAdd'\)\.addEventListener/);
  assert.match(main, /import \{ AdminRegistrationPanel \} from "\.\/registration-panel\.js"/);
  assert.match(main, /const registrationMount = document\.getElementById\("adminRegistrationReactApp"\)/);
  assert.match(main, /createRoot\(registrationMount\)\.render\(h\(AdminRegistrationPanel\)\)/);
  assert.match(panel, /import \{ AdminRegistrationManualPlayerForm \} from "\.\/registration-manual-player-form\.js"/);
  assert.match(panel, /import \{ AdminRegistrationRoster \} from "\.\/registration-roster\.js"/);
  assert.match(panel, /h\(AdminRegistrationManualPlayerForm/);
  assert.match(panel, /h\(AdminRegistrationRoster/);
  assert.match(manualForm, /export function AdminRegistrationManualPlayerForm/);
  assert.match(manualForm, /gvdg:admin-registration-manual-player-add-request/);
  assert.match(manualForm, /gvdg:admin-registration-manual-player-add-result/);
  assert.match(manualForm, /data-react-admin-registration-manual-player-form/);
  assert.match(roster, /export function AdminRegistrationRoster/);
  assert.match(roster, /import \{ ManualPlayerRow, RegistrationRow \} from "\.\/registration-roster-rows\.js"/);
  assert.match(roster, /gvdg:admin-registration-roster/);
  assert.match(rosterSurface, /gvdg:admin-registration-roster-patch-request/);
  assert.match(rosterSurface, /gvdg:admin-registration-roster-credit-request/);
  assert.match(rosterSurface, /gvdg:admin-registration-manual-remove-request/);
  assert.doesNotMatch(roster, /currentAdminState\("registrationRoster"|admin-state-store|function currentRosterState/);
  assert.match(roster, /data-react-admin-registration-roster/);
  assert.match(rows, /export function RegistrationRow/);
  assert.match(rows, /export function ManualPlayerRow/);
  assert.match(rows, /data-admin-registration-id/);
  assert.match(rows, /data-admin-registration-manual-id/);
  assert.match(roster, /className: "al-holes"/);
  assert.match(rows, /className: "credit-award"/);
  assert.match(roster, /role: "status"/);
  assert.match(roster, /role: "alert"/);
  assert.doesNotMatch(rosterSurface, /innerHTML|insertAdjacentHTML|replaceChildren|document\.createElement|querySelector|classList|textContent\s*=|☰|✕|🌙|☀️|🏆|⚠|⏱|—/);
});
